# Generated by Django 3.2.15 on 2022-09-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shortenurl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenurl',
            name='validity',
            field=models.IntegerField(default=3),
        ),
    ]
