# Generated by Django 3.2.15 on 2022-09-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_shortenurl_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenurl',
            name='validity',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
